# H2 Database
spring.datasource.url=jdbc:h2:mem:base
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=hornet
spring.datasource.password=assjim
spring.security.user.name=hornet
spring.security.user.password=assjim
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# H2 Console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

